name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install prerequisite
        run: sudo apt-get install libgtk2.0-0t64 libgtk-3-0t64 libgbm-dev libnotify-dev libnss3 libxss1 libasound2t64 libxtst6 xauth xvfb
        
      - name: Init npm
        run: npm init -y

      - name: Install Cypress
        run: npm install cypress
        # run: npm install cypress --save-dev

      - name: Check Cypress version
        run: sudo npx cypress -v
        
      # - name: Cypress verify
      #   run: sudo npx cypress verify

      - name: Run Cypress tests
        run: sudo npx cypress run
