name: Cypress Tests with Dependency and Artifact Caching

on: push

env:
  # Set up the Cypress Cloud project ID and record key as environment variables
  # If the Actions secret EXAMPLE_PROJECT_ID is not defined then
  # the projectId is taken from cypress.json (v9) or cypress.config.js (v10 and later).
  # If the Actions secret EXAMPLE_RECORDING_KEY is not defined then recording jobs are skipped.
  # CYPRESS_PROJECT_ID: ${{ secrets.EXAMPLE_PROJECT_ID }}
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  install:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0

      - name: Install dependencies
        run: npm install

  cypress-run:
    runs-on: ubuntu-24.04
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          # start: npm start
          browser: chrome #firefox / edge / electron=default
          record: true
          # spec: cypress/e2e/spec1.cy.js
          # spec: |
          #   cypress/e2e/spec-a.cy.js
          #   cypress/**/*-b.cy.js
        env:
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass the project ID from the secrets through environment variable
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots
          if-no-files-found: ignore 
        # with:
        #   name: build
        #   if-no-files-found: error
        #   path: build


# name: Cypress Tests with Dependency and Artifact Caching 

# on: push
 
# jobs:
#   install:
#     runs-on: ubuntu-24.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4.1.0
#         # with:
#         #   node-version: 20

#       - name: Install dependencies
#         run: npm install

#       - name: Cypress install
#         uses: cypress-io/github-action@v6
#         with:
#           # Disable running of tests within install job
#           runTests: false
#           build: npm run build

#       - name: Save build folder
#         uses: actions/upload-artifact@v4
#         with:
#           name: build
#           if-no-files-found: error
#           path: build

#   cypress-run:
#     runs-on: ubuntu-24.04
#     needs: install
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Download the build folder
#         uses: actions/download-artifact@v4
#         with:
#           name: build
#           path: build

#       - name: Cypress run
#         uses: cypress-io/github-action@v6
#         with:
#           start: npm start
#           browser: chrome
